name: doc

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: pip install --upgrade pip

      - run: pip install -v -e .[doc]

      - name: Make docs
        run: sphinx-build -W docs/source docs/build

      - name: Save docs
        uses: actions/upload-artifact@v5
        with:
          name: html-docs
          path: docs/build

  lint-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run language-agnostic linters
        uses: pre-commit/action@v3.0.1
